//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddressBook.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Addresses
    {
        public Addresses()
        {
            this.Contacts = new HashSet<Contacts>();
        }
    
        public int AddressId { get; set; }

        [Required(ErrorMessageResourceName = "CountryRequired", ErrorMessageResourceType = typeof(Resources.Models))]
        [Display(Name = "Country", ResourceType = typeof(Resources.Models))]
        public string Country { get; set; }

        [Required(ErrorMessageResourceName = "CityRequired", ErrorMessageResourceType = typeof(Resources.Models))]
        [Display(Name = "City", ResourceType = typeof(Resources.Models))]
        public string City { get; set; }

        [Required(ErrorMessageResourceName = "StreetRequired", ErrorMessageResourceType = typeof(Resources.Models))]
        [Display(Name = "Street", ResourceType = typeof(Resources.Models))]
        public string Street { get; set; }

        [Required(ErrorMessageResourceName = "HouseRequired", ErrorMessageResourceType = typeof(Resources.Models))]
        [Display(Name = "House", ResourceType = typeof(Resources.Models))]
        public string House { get; set; }

        [Required(ErrorMessageResourceName = "RoomRequired", ErrorMessageResourceType = typeof(Resources.Models))]
        [Display(Name = "Room", ResourceType = typeof(Resources.Models))]
        public string Room { get; set; }
    
        public virtual ICollection<Contacts> Contacts { get; set; }
    }
}
