//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddressBook.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Contacts
    {
        public int ContactsId { get; set; }

        [Required(ErrorMessageResourceName = "FirstNameRequired", ErrorMessageResourceType = typeof(Resources.Models))]
        [Display(Name = "FirstName", ResourceType = typeof(Resources.Models))]
        public string FirstName { get; set; }

        [Display(Name = "MiddleName", ResourceType = typeof(Resources.Models))]
        public string MiddleName { get; set; }

        [Required(ErrorMessageResourceName = "LastNameRequired", ErrorMessageResourceType = typeof(Resources.Models))]
        [Display(Name = "LastName", ResourceType = typeof(Resources.Models))]
        public string LastName { get; set; }

        [Required(ErrorMessageResourceName = "PhoneRequired", ErrorMessageResourceType = typeof(Resources.Models))]
        [Display(Name = "Phone", ResourceType = typeof(Resources.Models))]
        public string Phone { get; set; }

        public int AddressId { get; set; }

        [Required(ErrorMessageResourceName = "EmailRequired", ErrorMessageResourceType = typeof(Resources.Models))]
        [Display(Name = "Email", ResourceType = typeof(Resources.Models))]
        public string Email { get; set; }

        public int TypeId { get; set; }
        public int UserId { get; set; }
    
        public virtual Addresses Addresses { get; set; }
        public virtual Types Types { get; set; }
    }
}
